version: '3'
services:
  db:
    image: genschsa/mysql-employees
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - "3306:3306"
  app:
    build: .
    depends_on:
      - db