@startuml

actor HR as "HR Advisor"
actor DM as "Department Manager"

rectangle Database

rectangle "HR System" {
    usecase UC1 as "Get all salaries"
    usecase UC2 as "Get salaries by department"
    usecase UC3 as "Get salaries by department (Manager)"
    usecase UC4 as "Get salaries by role"
    usecase UC5 as "Add employee details"
    usecase UC6 as "View employee details"
    usecase UC7 as "Update employee details"
    usecase UC8 as "Delete employee details"

    usecase UCa as "Print salaries"

    HR - UC1
    HR - UC2
    DM - UC3
    HR - UC4
    HR - UC5
    HR - UC6
    HR - UC7
    HR - UC8

    UC1 ..> UCa : include
    UC2 ..> UCa : include
    UC3 ..> UCa : include
    UC4 ..> UCa : include

    UC1 - Database
    UC2 - Database
    UC3 - Database
    UC4 - Database
    UC5 - Database
    UC6 - Database
    UC7 - Database
    UC8 - Database
}

@enduml